[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { version = "0.32", features = ["cli"] }
librqbit = "8.1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tempfile = "3"
